# Generated by Django 5.0.1 on 2024-02-05 04:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0002_rename_rating_comment_comment_rating_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='comment',
            old_name='one_to_many_relation',
            new_name='one_to_many_relation_posts',
        ),
    ]
